version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: foreverSmile
      MYSQL_DATABASE: MyLibrary
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile   # Change to Dockerfile.backend if needed
    container_name: backend
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile   # Change to Dockerfile.frontend if needed
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
